### ISSUE TITLE
Demo data has install.php in the URLs

### ISSUE THREAD

**Issue by mrkschan** [goalgorilla/platformsh-example-opensocial#3]
With the demo data, the URL is having install.php in it.

{code}

```
        <p><a href="/core/install.php/user/6/stream">Michelle Clark</a> and 1 others commented on content in the group <a href="/core/install.php/group/2/stream">Local School Group Springfield</a></p>      
```

{code}

Sample installaton: http://master-7rqtwti-iiakjzgwmmbko.us.platform.sh/

**Comment by jaapjan** [comment]
This issue should be fixed now, see: https://www.drupal.org/node/2810015
